### ISSUE TITLE
Copying Image to G Drive

### ISSUE THREAD

**Issue by vvishwa** [Qengineering/RPiMotionCam#4]
I believe to have setup g drive correctly, I can see good output of $gdrive files list
I get email when there is motion, so motion detection and all that works fine. I am wondering though when detected pictures are store on gdrive?

**Comment by Qengineering** [comment]
Do you see the [settings](https://github.com/Qengineering/RPiMotionCam/wiki/Settings)? And have you applied the right ones?

**Comment by vvishwa** [comment]
It works now after I changed to
recording = 1
